name: autofix.ci

on:
  pull_request:
  push:
    branches: ["main"]
permissions:
  contents: read

jobs:
  autofix:
    name: Prettier formatting & autofix.ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Prepare environment
        uses: ./.github/actions/prepare-env

      - name: Format
        run: pnpm format

      - name: Update push/PR
        uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
