name: Release

on:
  push:
    branches: ["main"]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Prepare environment
        uses: ./.github/actions/prepare-env
      - name: Install cargo-bump from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-bump
          version: "1.1.0"

      - name: Create Release PR
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # TODO https://github.com/changesets/action/issues/147
          HOME: ${{ github.workspace }}
        with:
          version: pnpm ci:version

      - name: Publish
        if: steps.changesets.outputs.hasChangesets == 'false'
        uses: tauri-apps/tauri-action@v0.6.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
        with:
          tagName: v__VERSION__
          releaseName: v__VERSION__
          releaseBody: >-
            See the assets to download this version and install with `animethemes-encoder___VERSION___x64_en-US.msi`.


            **You need an internet connection** in case the installer needs to download the WebView2 bootstrapper.
